version: '3'

services:
  app:
    build: .
    ports:
      - 8088:80
    container_name: ngnix-front
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - nginx
networks:
  nginx:
    driver: bridge
